# Generated by Django 5.0.6 on 2025-06-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('duracion', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('en_linea', 'En línea'), ('hibrido', 'Híbrido')], max_length=20)),
                ('activo', models.BooleanField(default=False)),
                ('imagen', models.ImageField(null=True, upload_to='fots', verbose_name='Fotografía')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
