# Generated by Django 5.0.6 on 2025-06-30 17:38

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_options_alter_cursos_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('instituto', ckeditor.fields.RichTextField(verbose_name='Instituto')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Instituto',
                'verbose_name_plural': 'Instituto',
                'ordering': ['-created'],
            },
        ),
    ]
