# Generated by Django 5.0.6 on 2025-06-30 19:47

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_instituto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='descripcion',
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('descripcion', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Descripcion',
                'verbose_name_plural': 'Descripcion',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Instituto',
        ),
    ]
