# Generated by Django 5.0.6 on 2025-07-01 15:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_remove_cursos_descripcion_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('actividad', ckeditor.fields.RichTextField(verbose_name='Actividad')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividad',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Descripcion',
        ),
    ]
